

POST 8080-white-slug-2vphg0pw.ws-eu21.gitpod.io/users/create HTTP/1.1
content-type: application/json
{
    "firstName": "Admin",
    "lastName": "Test",
    "uniID": "ABCDE",
    "password": "admin123",
}